# Generated by Django 4.1.3 on 2022-11-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='econtact',
            field=models.IntegerField(),
        ),
    ]
